# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2048M

# Mod properties
mod_version=1.6.0
maven_group=net.satisfy
archives_base_name=vinery
enabled_platforms=fabric

# Minecraft properties
minecraft_version=26.3-rc-2

# Dependencies
architectury_version=21.1.9
rei_version=26.2.821
jei_minecraft_version=26.2
jei_version=30.32.0.215
cloth_fabric_version=26.2.155
mod_menu_version=21.0.0-beta.1
fabric_loader_version=0.19.5
fabric_api_version=0.160.4+26.3
neo_forge_version=26.2.0.88
